CREATE TABLE `Country` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CountryName` VARCHAR(35) NOT NULL DEFAULT '',
  `CountryDialingCode` VARCHAR(20) NOT NULL DEFAULT '',
  `ISO_CODE2` CHAR(2) NOT NULL DEFAULT '',
  `ISO_CODE3` CHAR(3) NOT NULL DEFAULT '',
  `Capital` VARCHAR(30) NOT NULL DEFAULT '',
  `Population` INT UNSIGNED NOT NULL DEFAULT 0,
  `AreaInKm2` INT UNSIGNED NOT NULL DEFAULT 0,
  `GDPinUSD` BIGINT UNSIGNED NULL DEFAULT NULL,
  `CurrencyName` VARCHAR(30) NOT NULL DEFAULT '',
  `CurrencyAbbreviation` CHAR(3) NOT NULL DEFAULT '',
  `CurrencySign` VARCHAR(5) NOT NULL DEFAULT '',
  `CurrencyRateUSD` DECIMAL(16,4) NULL DEFAULT NULL,
  `CurrencyRateUpdated` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `State` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `StateName` VARCHAR(30) NOT NULL DEFAULT '',
  `StateAbbreviation` CHAR(2) NOT NULL DEFAULT '',
  `Capital` VARCHAR(30) NOT NULL DEFAULT '',
  `Population` INT UNSIGNED NOT NULL DEFAULT 0,
  `AreaInKm2` INT UNSIGNED NOT NULL DEFAULT 0,
  `GDPinUSD` BIGINT UNSIGNED NULL DEFAULT NULL,
  `CountryId` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  KEY `CountryId` (`CountryId`),
  CONSTRAINT `FK_State_CountryId` FOREIGN KEY (`CountryId`) REFERENCES `Country` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `Company` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CompanyName` VARCHAR(30) NOT NULL DEFAULT '',
  `Address1` VARCHAR(50) NOT NULL DEFAULT '',
  `Address2` VARCHAR(50) DEFAULT NULL,
  `Building` VARCHAR(30) DEFAULT NULL,
  `City` VARCHAR(30) NOT NULL DEFAULT '',
  `StateId` SMALLINT UNSIGNED NOT NULL,
  `ZipCode` INT UNSIGNED NULL DEFAULT NULL,
  `CountryId` SMALLINT UNSIGNED NOT NULL,
  `Phone` BIGINT UNSIGNED NULL DEFAULT NULL,
  `LastUpdated` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `StateId` (`StateId`),
  CONSTRAINT `FK_Company_StateId` FOREIGN KEY (`StateId`) REFERENCES `State` (`id`),
  KEY `CountryId` (`CountryId`),
  CONSTRAINT `FK_Company_CountryId` FOREIGN KEY (`CountryId`) REFERENCES `Country` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `Employees` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(25) NOT NULL DEFAULT '',
  `MiddleName` VARCHAR(25) DEFAULT '',
  `LastName` VARCHAR(30) NOT NULL DEFAULT '',
  `JobDescription` VARCHAR(40) NOT NULL DEFAULT '',
  `Email` VARCHAR(50) NOT NULL DEFAULT '',
  `SkypeName` VARCHAR(30) NULL DEFAULT '',
  `CellPhone` BIGINT UNSIGNED NULL DEFAULT NULL,
  `CellPhoneCountryPrefix` SMALLINT(4) UNSIGNED NULL DEFAULT NULL,
  `CompanyId` SMALLINT UNSIGNED NOT NULL,
  `DateStarted` DATE NOT NULL,
  `DateTerminated` DATE NULL DEFAULT NULL,
  `Active` BIT(1) NOT NULL,
  `LastUpdated` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `CompanyId` (`CompanyId`),
  CONSTRAINT `FK_Employees_CompanyId` FOREIGN KEY (`CompanyId`) REFERENCES `Company` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
