CREATE TABLE `FootballWorldCup` (
  `year` SMALLINT UNSIGNED NOT NULL,
  `HostCountry1Id` SMALLINT UNSIGNED NOT NULL,
  `HostCountry2Id` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `HostCountry3Id` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `1stPlacedCountryId` SMALLINT UNSIGNED NOT NULL,
  `2ndPlacedCountryId` SMALLINT UNSIGNED NOT NULL,
  `3rdPlacedCountryId` SMALLINT UNSIGNED NOT NULL,
  `4thPlacedCountryId` SMALLINT UNSIGNED NOT NULL,
  `1stPlacedLastGameScore` TINYINT UNSIGNED NOT NULL,
  `2ndPlacedLastGameScore` TINYINT UNSIGNED NOT NULL,
  `3rdPlacedLastGameScore` TINYINT UNSIGNED NOT NULL,
  `4thPlacedLastGameScore` TINYINT UNSIGNED NOT NULL,
  `numberOfTeams` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`year`),
  KEY `HostCountry1Id` (`HostCountry1Id`),
  KEY `HostCountry2Id` (`HostCountry2Id`),
  KEY `HostCountry3Id` (`HostCountry3Id`),
  KEY `1stPlacedCountryId` (`1stPlacedCountryId`),
  KEY `2ndPlacedCountryId` (`2ndPlacedCountryId`),
  KEY `3rdPlacedCountryId` (`3rdPlacedCountryId`),
  KEY `4thPlacedCountryId` (`4thPlacedCountryId`),
  CONSTRAINT `HostCountry1Id` FOREIGN KEY (`HostCountry1Id`) REFERENCES `Country` (`id`),
  CONSTRAINT `HostCountry2Id` FOREIGN KEY (`HostCountry2Id`) REFERENCES `Country` (`id`),
  CONSTRAINT `HostCountry3Id` FOREIGN KEY (`HostCountry3Id`) REFERENCES `Country` (`id`),
  CONSTRAINT `1stPlacedCountryId` FOREIGN KEY (`1stPlacedCountryId`) REFERENCES `Country` (`id`),
  CONSTRAINT `2ndPlacedCountryId` FOREIGN KEY (`2ndPlacedCountryId`) REFERENCES `Country` (`id`),
  CONSTRAINT `3rdPlacedCountryId` FOREIGN KEY (`3rdPlacedCountryId`) REFERENCES `Country` (`id`),
  CONSTRAINT `4thPlacedCountryId` FOREIGN KEY (`4thPlacedCountryId`) REFERENCES `Country` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

