name: dev SmartHome web CI

on:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Who am I
              run: whoami

            - name: List directory
              run: ls -la

            - name: Home, Shell
              run: |
                echo "\$HOME = $HOME"
                echo "\$SHELL = $SHELL"
                bash --version
                which bash
                which rsync
