name: dev SmartHome web CI

on:
    push:
        branches:
            - dev
            - test
            - master


jobs:
    Deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: GitHub Environment Variables Action
              uses: FranzDiebold/github-env-vars-action@v1

            - name: List directory
              run: ls -la

            - name: Set ENVIRONMENT to dev
              if: endsWith(github.ref, '/dev')
              run: echo "::set-env name=ENVIRONMENT::dev"

            - name: Set ENVIRONMENT to test
              if: endsWith(github.ref, '/test')
              run: echo "::set-env name=ENVIRONMENT::test"

            - name: Set ENVIRONMENT to prod
              if: endsWith(github.ref, '/master')
              run: echo "::set-env name=ENVIRONMENT::prod"

            - name: Print out ENVIRONMENT variable
              run: echo "\$ENVIRONMENT =  $ENVIRONMENT"

            - name: "Sync to hosting website: $GITHUB_REF_NAME"
              run: |
                echo "\$HOME = $HOME"
                echo "\$SHELL = $SHELL"
                which bash
                bash --version
                which rsync
                rsync --version
                echo "\$GITHUB_REF = $GITHUB_REF"
                echo "\$GITHUB_REF_NAME = $GITHUB_REF_NAME"
